version: '2'
services:
  nginx:
    build: nginx
    command: nginx -g "daemon off;"
    links:
      - tomcat
    container_name: app_nginx
    ports:
      - "5000:80"
    networks:
      - nginx_network
  tomcat:
    build: tomcat
    working_dir: /usr/local/tomcat
    command: catalina.sh run
    container_name: app_tomcat
    ports:
      - "8080"
    volumes:
      - ./tomcat/webapps/flowable-rest:/usr/local/tomcat/webapps/flowable-rest
      - ./tomcat/webapps/flowable-ui:/usr/local/tomcat/webapps/flowable-ui
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge